const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d'),startEl=document.querySelector('#start'),gameEl=document.querySelector('#game'),dialogue=document.querySelector('#dialogue'),toast=document.querySelector('#toast');
const W=1600,H=1000,KEY='jornada-vila-v3';let running=false,last=0,keys={},near=null,dialogOpen=false;
let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(error){localStorage.removeItem(KEY)}
let saveData={name:'Ian',lights:0,inventory:[],x:790,y:720,...stored,missions:{bola:0,compras:0,lixo:0,...(stored.missions||{})}};
const player={x:saveData.x||790,y:saveData.y||720,r:22,speed:220,dir:'down'},camera={x:0,y:0};
const solids=[{x:80,y:90,w:280,h:210},{x:610,y:70,w:330,h:230},{x:1190,y:100,w:300,h:220},{x:80,y:650,w:300,h:240},{x:1190,y:670,w:300,h:220},{x:720,y:420,w:170,h:105}];
const trees=[[430,120],[490,200],[1050,130],[1090,240],[450,790],[530,860],[1040,790],[1110,880],[150,480],[1450,500],[1010,470],[560,470],[370,390],[1250,410]];
trees.forEach(([x,y])=>solids.push({x:x-24,y:y-28,w:48,h:52}));
const npcs=[{id:'leo',x:475,y:350,emoji:'🧒🏻',name:'Léo'},{id:'marta',x:1110,y:580,emoji:'👵🏽',name:'Dona Marta'},{id:'davi',x:540,y:650,emoji:'🧑🏾',name:'Davi'}];
const items=[{id:'bola',x:1040,y:845,emoji:'⚽',label:'Bola'},{id:'compras',x:1370,y:570,emoji:'🛍️',label:'Sacolas'},{id:'lixo1',x:940,y:390,emoji:'🧃',label:'Lixo'},{id:'lixo2',x:680,y:610,emoji:'🥫',label:'Lixo'},{id:'lixo3',x:1020,y:660,emoji:'📄',label:'Lixo'}];
const flowers=[[410,540],[445,570],[1140,450],[1180,470],[900,830],[840,850],[260,560],[1320,430]];
const save=()=>{saveData.x=Math.round(player.x);saveData.y=Math.round(player.y);localStorage.setItem(KEY,JSON.stringify(saveData))};
function missionDone(id){return saveData.missions[id]===2}function allDone(){return ['bola','compras','lixo'].every(missionDone)}
function activeItems(){return items.filter(i=>{if(i.id==='bola')return saveData.missions.bola===1&&!saveData.inventory.includes('bola');if(i.id==='compras')return saveData.missions.compras===1&&!saveData.inventory.includes('compras');if(i.id.startsWith('lixo'))return saveData.missions.lixo===1&&!saveData.inventory.includes(i.id);return false})}
function showToast(text){toast.textContent=text;toast.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.hidden=true,1700)}
function say(who,text,button='Continuar',after){dialogOpen=true;dialogue.innerHTML=`<div class="who">${who}</div><p>${text}</p><button>${button}</button>`;dialogue.hidden=false;dialogue.querySelector('button').onclick=()=>{dialogue.hidden=true;dialogOpen=false;if(after)after()}}
function award(id,n,msg){saveData.missions[id]=2;saveData.lights+=n;document.querySelector('#lights').textContent=saveData.lights;save();showToast(`✨ +${n} luzes — ${msg}`)}
function talk(n){if(n.id==='leo'){if(saveData.missions.bola===0)say('Léo','Oi! Minha bola rolou para perto do bosque e eu não consigo encontrá-la. Você pode procurar para mim?','Vou procurar!',()=>{saveData.missions.bola=1;save();updateQuest()});else if(saveData.inventory.includes('bola'))say('Léo','Você encontrou! Agora podemos brincar juntos. Obrigado por não me deixar sozinho!','Entregar a bola',()=>{saveData.inventory=saveData.inventory.filter(x=>x!=='bola');award('bola',2,'Amigo Bondoso');updateQuest()});else if(missionDone('bola'))say('Léo','Foi muito legal você ter me ajudado. A bondade deixa a vila mais feliz!');else say('Léo','A bola deve estar no bosque, perto das flores amarelas.');}
 else if(n.id==='marta'){if(saveData.missions.compras===0)say('Dona Marta','Estas sacolas estão pesadas. Deixei algumas perto do mercado. Você poderia buscá-las e trazer até mim?','Pode deixar!',()=>{saveData.missions.compras=1;save();updateQuest()});else if(saveData.inventory.includes('compras'))say('Dona Marta','Que alívio! Servir alguém é uma forma de seguir o exemplo de Jesus.','Entregar as sacolas',()=>{saveData.inventory=saveData.inventory.filter(x=>x!=='compras');award('compras',2,'Ajudante da Vila');updateQuest()});else if(missionDone('compras'))say('Dona Marta','Obrigada novamente, querido. Uma pequena ajuda pode significar muito.');else say('Dona Marta','As sacolas ficaram perto do mercado, no lado direito da vila.');}
 else{const trash=saveData.inventory.filter(x=>x.startsWith('lixo')).length;if(saveData.missions.lixo===0)say('Davi','O vento espalhou três lixos pela praça. Vamos cuidar juntos do lugar que Deus nos deu?','Vamos!',()=>{saveData.missions.lixo=1;save();updateQuest()});else if(trash===3)say('Davi','Você encontrou todos! Cuidar do mundo também demonstra gratidão.','Colocar na lixeira',()=>{saveData.inventory=saveData.inventory.filter(x=>!x.startsWith('lixo'));award('lixo',3,'Guardião da Praça');updateQuest()});else if(missionDone('lixo'))say('Davi','A praça ficou bonita outra vez. Obrigado por cuidar dela!');else say('Davi',`Você já recolheu ${trash} de 3. Continue procurando pela praça.`)}}
function interact(){if(dialogOpen)return;if(near?.type==='npc')talk(near.obj);else if(near?.type==='item'){const i=near.obj;saveData.inventory.push(i.id);save();showToast(`${i.emoji} ${i.label} colocado no inventário`);updateQuest()}else if(near?.type==='gate'){if(allDone())say('Lumi','Você iluminou toda a Vila da Bondade! Novas terras serão abertas em breve. Por enquanto, continue explorando e ajudando seus amigos.','Celebrar!');else say('Lumi','Este caminho se abrirá quando as três missões da vila estiverem completas.','Voltar à vila')}else showToast('Chegue perto de alguém ou de um objeto')}
function updateQuest(){let text;if(allDone())text='<b>Vila iluminada!</b> Vá até o portal dourado.';else{const open=[];if(saveData.missions.bola===1)open.push(saveData.inventory.includes('bola')?'Leve a bola ao Léo':'Encontre a bola no bosque');if(saveData.missions.compras===1)open.push(saveData.inventory.includes('compras')?'Leve as sacolas à Dona Marta':'Busque as sacolas no mercado');if(saveData.missions.lixo===1){const n=saveData.inventory.filter(x=>x.startsWith('lixo')).length;open.push(n===3?'Leve os lixos ao Davi':`Recolha os lixos da praça (${n}/3)`)}text=open.length?open.join(' • '):'Converse com os moradores marcados com <b>!</b>'}document.querySelector('#quest').innerHTML=text}
function collides(x,y){return x<28||y<28||x>W-28||y>H-28||solids.some(s=>x+18>s.x&&x-18<s.x+s.w&&y+20>s.y&&y-18<s.y+s.h)}
function update(dt){if(dialogOpen)return;let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(dx||dy){const len=Math.hypot(dx,dy);dx/=len;dy/=len;if(Math.abs(dx)>Math.abs(dy))player.dir=dx>0?'right':'left';else player.dir=dy>0?'down':'up';const nx=player.x+dx*player.speed*dt,ny=player.y+dy*player.speed*dt;if(!collides(nx,player.y))player.x=nx;if(!collides(player.x,ny))player.y=ny}camera.x=Math.max(0,Math.min(W-canvas.width,player.x-canvas.width/2));camera.y=Math.max(0,Math.min(H-canvas.height,player.y-canvas.height/2));near=null;let best=75;npcs.forEach(n=>{const d=Math.hypot(player.x-n.x,player.y-n.y);if(d<best){best=d;near={type:'npc',obj:n}}});activeItems().forEach(i=>{const d=Math.hypot(player.x-i.x,player.y-i.y);if(d<best){best=d;near={type:'item',obj:i}}});if(Math.hypot(player.x-800,player.y-42)<85)near={type:'gate'};save.loop=(save.loop||0)+dt;if(save.loop>2){save.loop=0;save()}}
function roundRect(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function text(t,x,y,size=28,align='center'){ctx.textAlign=align;ctx.textBaseline='middle';ctx.font=`${size}px "Apple Color Emoji","Segoe UI Emoji",sans-serif`;ctx.fillText(t,x,y)}
function drawBuilding(s,color,roof,label,emoji){roundRect(s.x,s.y+50,s.w,s.h-50,18,color);ctx.fillStyle=roof;ctx.beginPath();ctx.moveTo(s.x-20,s.y+65);ctx.lineTo(s.x+s.w/2,s.y-25);ctx.lineTo(s.x+s.w+20,s.y+65);ctx.closePath();ctx.fill();roundRect(s.x+s.w/2-28,s.y+s.h-75,56,75,10,'#76523c');text(emoji,s.x+s.w/2,s.y+s.h-38,30);ctx.fillStyle='#133652';ctx.font='800 20px system-ui';ctx.textAlign='center';ctx.fillText(label,s.x+s.w/2,s.y+s.h+28)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-camera.x,-camera.y);ctx.fillStyle='#94d27b';ctx.fillRect(0,0,W,H);ctx.fillStyle='#aadf91';for(let x=20;x<W;x+=65)for(let y=20;y<H;y+=65){ctx.beginPath();ctx.arc(x+(y%3)*8,y,3,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#efd7a4';roundRect(720,0,160,H,0,'#efd7a4');roundRect(0,430,W,160,0,'#efd7a4');roundRect(770,500,60,430,0,'#efd7a4');drawBuilding(solids[0],'#ffcfb3','#cf655e','Casa do Léo','🏠');drawBuilding(solids[1],'#e7ddbf','#557b9b','Capela','🌿');drawBuilding(solids[2],'#ffe8a7','#d7864e','Mercadinho','🧺');drawBuilding(solids[3],'#d8c8f1','#7566a9','Centro da Vila','🎨');drawBuilding(solids[4],'#ffd2d2','#c75858','Casa da Marta','🏡');roundRect(720,420,170,105,20,'#86cbed');ctx.fillStyle='#b9e5fa';ctx.beginPath();ctx.ellipse(805,472,72,34,0,0,Math.PI*2);ctx.fill();text('⛲',805,465,45);flowers.forEach(([x,y])=>text('🌼',x,y,22));trees.forEach(([x,y])=>{ctx.fillStyle='#76523c';ctx.fillRect(x-8,y,16,32);text('🌳',x,y-15,48)});ctx.fillStyle=allDone()?'#ffd05a':'#80939b';roundRect(730,0,140,55,14,ctx.fillStyle);text(allDone()?'✨ PORTAL ✨':'🔒 PORTAL',800,28,20);npcs.forEach(n=>{const shadowY=n.y+23;ctx.fillStyle='#21475b33';ctx.beginPath();ctx.ellipse(n.x,shadowY,22,9,0,0,Math.PI*2);ctx.fill();text(n.emoji,n.x,n.y,42);if(!missionDone(n.id==='leo'?'bola':n.id==='marta'?'compras':'lixo')){text('!',n.x,n.y-43,25);}});activeItems().forEach(i=>{ctx.fillStyle='#fff9';ctx.beginPath();ctx.arc(i.x,i.y,28,0,Math.PI*2);ctx.fill();text(i.emoji,i.x,i.y,34)});const lx=player.x-34,ly=player.y-42;ctx.fillStyle='#ffd05a';ctx.beginPath();ctx.arc(lx,ly,15,0,Math.PI*2);ctx.fill();text('★',lx,ly,18);ctx.fillStyle='#21475b33';ctx.beginPath();ctx.ellipse(player.x,player.y+24,24,9,0,0,Math.PI*2);ctx.fill();text('🧒🏽',player.x,player.y,45);if(near){ctx.strokeStyle='#ffd05a';ctx.lineWidth=4;ctx.beginPath();ctx.arc(player.x,player.y,34+Math.sin(performance.now()/160)*3,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function loop(t){if(!running)return;const dt=Math.min(.035,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
function start(){saveData.name=document.querySelector('#player-name').value.trim()||'Ian';document.querySelector('#name-hud').textContent=saveData.name;document.querySelector('#lights').textContent=saveData.lights;startEl.hidden=true;gameEl.hidden=false;running=true;updateQuest();resize();requestAnimationFrame(loop);save()}
function resize(){const ratio=Math.min(innerWidth/960,innerHeight/600);canvas.style.width=`${960*ratio}px`;canvas.style.height=`${600*ratio}px`;canvas.style.position='absolute';canvas.style.left=`${(innerWidth-960*ratio)/2}px`;canvas.style.top=`${(innerHeight-600*ratio)/2}px`}
document.querySelector('#play').onclick=start;document.querySelector('#action').onclick=interact;addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if((e.key===' '||e.key==='Enter')&&running)interact()});addEventListener('keyup',e=>keys[e.key]=false);addEventListener('resize',resize);const directionKeys={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'};document.querySelectorAll('[data-dir]').forEach(button=>{const key=directionKeys[button.dataset.dir];const stop=event=>{event.preventDefault();keys[key]=false};button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);keys[key]=true},{passive:false});button.addEventListener('pointerup',stop,{passive:false});button.addEventListener('pointercancel',stop,{passive:false});button.addEventListener('lostpointercapture',stop,{passive:false})});['contextmenu','selectstart','dragstart'].forEach(type=>gameEl.addEventListener(type,event=>event.preventDefault()));document.querySelector('#player-name').value=saveData.name;if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
