const KEY="jornada-discipulo-v2";
const initial={name:"Ian",lights:0,completed:[],screen:"welcome"};
let state={...initial,...JSON.parse(localStorage.getItem(KEY)||"{}")};
const app=document.querySelector("#app");
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function shell(content,cls=""){app.innerHTML=`<section class="screen"><div class="card ${cls}">${content}</div></section>`}
function render(){({welcome, map, kindness, covenant, scriptures, ending}[state.screen]||welcome)()}
function welcome(){shell(`<div class="hero-mark">⭐</div><span class="badge">UMA AVENTURA DE FÉ</span><h1>Jornada do<br>Discípulo</h1><p class="lead">Explore lugares, ajude pessoas e descubra como seguir Jesus todos os dias.</p><div class="field"><label for="name">Nome do aventureiro</label><input id="name" maxlength="16" value="${esc(state.name)}" autocomplete="off"></div><button class="primary" id="start">Entrar no mapa →</button><p class="tiny">Seu progresso fica salvo neste aparelho.</p>`,`center`);document.querySelector("#start").onclick=()=>{state.name=document.querySelector("#name").value.trim()||"Ian";state.screen="map";save();render()}}
function header(){return `<div class="topbar"><div class="player"><span class="avatar">🧒🏽</span>${esc(state.name)}</div><div class="light-count">✨ ${state.lights}</div></div>`}
function map(){const unlocked=n=>n===0||state.completed.includes(n-1);const missions=[['🤝','Vila da Bondade','Ajude alguém a se sentir incluído'],['💧','Rio dos Convênios','Organize os passos do caminho'],['📖','Biblioteca das Escrituras','Encontre pistas das histórias']];shell(`${header()}<div class="map-title"><span class="badge">MAPA DA JORNADA</span><h2>Para onde vamos?</h2></div><div class="map">${missions.map((m,i)=>`<button class="mission ${!unlocked(i)?'locked':''} ${state.completed.includes(i)?'done':''}" data-mission="${i}" ${!unlocked(i)?'disabled':''}><span class="mission-icon">${m[0]}</span><span><strong>${m[1]}</strong><small>${m[2]}</small></span><span class="status">${state.completed.includes(i)?'✓':unlocked(i)?'→':'🔒'}</span></button>`).join('')}</div><div class="lumi"><span>⭐</span><div><strong>Lumi diz:</strong><br>${state.completed.length?"Cada missão acende uma nova luz. Continue!":"Comece pela Vila da Bondade. Suas escolhas abrem o caminho!"}</div></div>`);document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{state.screen=['kindness','covenant','scriptures'][+b.dataset.mission];render()})}
function finishMission(id,lights){if(!state.completed.includes(id)){state.completed.push(id);state.lights+=lights}save();if(state.completed.length===3){state.screen="ending";render()}else{state.screen="map";render()}}
function kindness(){let chosen=null;shell(`${header()}<div class="story-scene"><span class="badge">MISSÃO 1 • BONDADE</span><div class="scene-icon">🛝</div><h2>Alguém está sozinho</h2><div class="story-box">No recreio, ${esc(state.name)} percebe que uma criança nova está sentada sozinha enquanto todos brincam. Lumi pergunta: “O que um discípulo de Jesus faria?”</div><div class="choices"><button class="choice" data-good="1">🤝 Convidar a criança para brincar</button><button class="choice">🙈 Continuar brincando sem falar com ela</button><button class="choice">😆 Fazer uma piada sobre ela</button></div><div id="feedback"></div></div>`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{if(chosen)return;chosen=b;b.classList.add(b.dataset.good?'good':'bad');document.querySelector('#feedback').innerHTML=`<div class="feedback ${b.dataset.good?'success':''}"><strong>${b.dataset.good?'Você escolheu como Jesus escolheria! 💛':'Vamos tentar uma escolha mais bondosa.'}</strong><br>${b.dataset.good?'Incluir alguém é uma maneira de mostrar o amor do Salvador.':'Um discípulo percebe quem precisa de amizade e tenta ajudar.'}<button class="primary" id="continue">${b.dataset.good?'Receber luz e continuar':'Tentar novamente'}</button></div>`;document.querySelector('#continue').onclick=()=>b.dataset.good?finishMission(0,2):kindness()})}
function covenant(){let items=['Dom do Espírito Santo','Fé em Jesus Cristo','Perseverar até o fim','Batismo','Arrependimento'];const correct=['Fé em Jesus Cristo','Arrependimento','Batismo','Dom do Espírito Santo','Perseverar até o fim'];function draw(){shell(`${header()}<div class="center"><span class="badge">MISSÃO 2 • CONVÊNIOS</span><div class="scene-icon">🌊</div><h2>Construa a ponte</h2><p class="lead">Coloque os passos do evangelho na ordem correta para atravessar o Rio dos Convênios.</p></div><div class="order-list">${items.map((x,i)=>`<div class="order-item"><span class="number">${i+1}</span><span>${x}</span><span class="order-actions"><button data-up="${i}" aria-label="Mover para cima">↑</button><button data-down="${i}" aria-label="Mover para baixo">↓</button></span></div>`).join('')}</div><div class="center"><button class="primary" id="check">Testar a ponte</button><div id="feedback"></div></div>`);document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.up;if(i){[items[i-1],items[i]]=[items[i],items[i-1]];draw()}});document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{const i=+b.dataset.down;if(i<items.length-1){[items[i+1],items[i]]=[items[i],items[i+1]];draw()}});document.querySelector('#check').onclick=()=>{const ok=items.every((x,i)=>x===correct[i]);document.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'success':''}"><strong>${ok?'A ponte está completa! 🌈':'A ponte ainda precisa de ajustes.'}</strong><br>${ok?'Esses passos formam o caminho do evangelho de Jesus Cristo.':'Dica: o caminho começa com fé em Jesus Cristo.'}${ok?'<button class="primary" id="continue">Atravessar o rio →</button>':''}</div>`;if(ok)document.querySelector('#continue').onclick=()=>finishMission(1,3)}}draw()}
function scriptures(){const objects=[['🐑','Ovelha',1],['👑','Coroa',0],['🛶','Arca',1],['⚽','Bola',0],['🧭','Liahona',1],['🎮','Controle',0]];let found=new Set();shell(`${header()}<div class="center"><span class="badge">MISSÃO 3 • ESCRITURAS</span><div class="scene-icon">📚</div><h2>Caça às pistas</h2><p class="lead">Encontre três objetos ligados a histórias das escrituras: algo que Jesus procuraria, o que Noé construiu e o guia da família de Leí.</p><div class="meter"><i id="meter" style="width:0"></i></div><div class="objects">${objects.map((o,i)=>`<button class="object" data-i="${i}">${o[0]}<span>${o[1]}</span></button>`).join('')}</div><div id="feedback"></div></div>`);document.querySelectorAll('.object').forEach(b=>b.onclick=()=>{const o=objects[+b.dataset.i];if(o[2]){found.add(+b.dataset.i);b.classList.add('found');b.disabled=true;document.querySelector('#meter').style.width=`${found.size/3*100}%`;if(found.size===3)document.querySelector('#feedback').innerHTML=`<div class="feedback success"><strong>Você encontrou todas as pistas! 📖</strong><br>As escrituras nos ajudam a conhecer Jesus e escolher o caminho certo.<button class="primary" id="continue">Completar jornada →</button></div>`,document.querySelector('#continue').onclick=()=>finishMission(2,3)}else{b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),300)}})}
function ending(){shell(`<div class="reward">🏆</div><span class="badge">JORNADA COMPLETA</span><h1>Você iluminou<br>todo o caminho!</h1><div class="medal">✨ ${state.lights} luzes conquistadas</div><p class="lead">${esc(state.name)}, você demonstrou bondade, aprendeu sobre convênios e explorou as escrituras. Um discípulo continua seguindo Jesus fora do jogo.</p><div class="lumi"><span>⭐</span><div><strong>Desafio da Lumi:</strong><br>Faça hoje uma boa ação sem ninguém pedir.</div></div><div class="actions"><button class="secondary" id="map">Ver o mapa</button><button class="primary" id="again">Jogar novamente ↻</button></div>`,`center`);document.querySelector('#map').onclick=()=>{state.screen='map';save();render()};document.querySelector('#again').onclick=()=>{state={...initial,name:state.name};save();render()}}
render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
